config/routes.rb
ShareCar::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'main#index'
  post "owners/new", to: "owners#create"
  resources :owners
  post "cars/new", to: "cars#create"
  resources :cars do
    member do
      delete "delete"
    end
  end
  get "loans/splitwise_callback", to: "loans#splitwise_callback"
  post "loans/new", to: "loans#create"
  resources :loans do
    member do
      delete "delete"
    end
    collection do
      get "create_multiple", as: :complete
    end
  end
  get "trips/increment", as: :increment
  get "trips/decrement", as: :decrement
  post "trips/new", to: "trips#create"
  resources :trips do
    member do
      get "show", as: :details
    end
    collection do
      post "join_multiple"
    end
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
    has_many :trips
    has_many :owner, dependent: :delete_all
    validates :make, :model, :year, :seats, :cost_per_mile, presence: true
    validates :cost_per_mile, numericality: {greater_than: 0}
    validates :seats, numericality: {only_integer: true, greater_than: 0}
    validates :year, numericality: {only_integer: true, greater_than: 1900}

    def human_name
    	"#{self.make} #{self.model} #{self.year}"
    end
end

app/models/trip.rb
class Trip < ActiveRecord::Base
    belongs_to :car
    has_many :passenger, dependent: :delete_all
    validates :distance, presence: true, numericality: {greater_than: 0}
    validates :origin, :destination, :car_id, :start_time, :end_time, presence: true
    validate :start_must_be_before_end_time
    validate :validate_total_trip_cost
    before_validation :default_values
    before_validation :round_distance, if: -> { distance.present? }
    before_validation :update_costs, if: -> { car_id.present? && distance.present? && distance > 0 }

    private

    def default_values
        self.completed = false if self.completed.nil?
        true
    end

    def update_costs
        number_of_passengers = 1
        if self.id
            number_of_passengers = [number_of_passengers, Passenger.where(trip_id: self.id).count].max
        end
        base_cost = Car.find(self.car_id).cost_per_mile * self.distance
        total_trip_cost = -1
        if number_of_passengers == 1
          total_trip_cost = base_cost * 1.2
        elsif number_of_passengers == 2 or number_of_passengers == 3
          total_trip_cost = base_cost * 1.1
        elsif number_of_passengers == 4
          total_trip_cost = base_cost * 1.05
        else
          total_trip_cost = base_cost
        end
        new_passenger_costs = {1 => 1.1, 2 => 1.1, 3 => 1.05, 4 => 1.0}
        new_passenger_cost = base_cost * new_passenger_costs[[4,number_of_passengers].min]/(number_of_passengers+1)
        self.assign_attributes(:total_trip_cost => total_trip_cost, :new_passenger_cost => new_passenger_cost)
    end

    def round_distance
    	#Rounding to 2 decimal places
    	self.distance = self.distance.round(2)
    end

    def start_must_be_before_end_time
    	return unless self.start_time and self.end_time
    	errors.add(:start_time, "must be before end time") unless
        	self.start_time < self.end_time
    end

    def validate_total_trip_cost
        return unless total_trip_cost.present?
        if total_trip_cost < 0
            errors.add(:total_trip_cost, "must not be negative")
        end
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :is_passenger, only: [:decrement, :edit, :update, :destroy]
  before_action :is_owner, only: [:edit, :destroy]

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
    @car = Car.find(@trip.car_id)
    @passengers = Passenger.where(trip_id: @trip.id)
  end

  def new
    @trip = Trip.new
    #@cars is a list of all the cars that current_user owns
    @cars = Owner.where(user_id: current_user.id).collect{ |o| [Car.find(o.car_id).human_name, o.car_id] }
    @url = trips_new_url
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      Passenger.create(user_id: current_user.id, trip_id: @trip.id)
      flash[:success] = "Successfully created trip!"
      redirect_to trips_path
    else
      flash.now[:error] = "Could not create trip. Please check the errors below."
      @cars = Owner.where(user_id: current_user.id).collect{ |o| [Car.find(o.car_id).human_name, o.car_id] }
      render "new"
    end
  end

  def edit
    @trip = Trip.find(params[:id])
    #@cars is a list of all the cars that current_user owns which have atleast as many seats as passengers in @trip
    @cars = Owner.where(user_id: current_user.id, car_id: Car.where('seats >= ?', Passenger.where(trip_id: @trip.id).count).pluck(:id)).collect{ |o| [Car.find(o.car_id).human_name, o.car_id] }
    @url = trip_url
  end

  def update
    trip = Trip.find(params[:id])
    if trip.update_attributes(trip_params)
      flash[:success] = "Trip updated successfully!"
      redirect_to details_trip_path(trip)
    else
      flash[:error] = "Could not update trip. Please check the details and try again."
      redirect_to trips_path
    end
  end

  ## TODO: Change name to something more meaningful
  ## TODO: If possible refactor this & decrement into one function
  def increment
    @trip = Trip.find(params[:id])
    #Now adding the record corresponding to (trip_id,user_id) to passengers table
    @passenger = Passenger.new(trip_id: @trip.id, user_id: current_user.id)
    if @passenger.save and @trip.save
      flash[:success] = "You've successfully joined this trip"
      redirect_to details_trip_path(@trip)
    else
      flash[:error] = "Failed to add passenger to trip"
      redirect_to trips_path
    end
  end

  def decrement
    @trip = Trip.find(params[:id])
    #Now removing the record corresponding to (trip_id,user_id) from passengers table
    passenger = Passenger.where(trip_id: @trip.id, user_id: current_user.id).first
    if passenger.destroy and @trip.save
      flash[:success] = "You've successfully left this trip"
      redirect_to details_trip_path(@trip)
    else
      flash[:error] = "Failed to remove passenger from trip"
      redirect_to trips_path
    end
  end

  def join_multiple
    trip_ids = params[:trip_ids] || []
    joined = []
    failed = []
    trip_ids.each do |trip_id|
      trip = Trip.find_by(id: trip_id)
      next unless trip
      next if trip.completed
      next if Passenger.where(trip_id: trip.id, user_id: current_user.id).present?
      next if Passenger.where(trip_id: trip.id).count >= Car.find(trip.car_id).seats
      passenger = Passenger.new(trip_id: trip.id, user_id: current_user.id)
      if passenger.save && trip.save
        joined << trip
      else
        failed << trip
      end
    end
    if joined.any?
      flash[:success] = "Successfully joined #{joined.length} trip(s)!"
    end
    if failed.any?
      flash[:error] = "Failed to join #{failed.length} trip(s)."
    end
    if joined.empty? && failed.empty?
      flash[:notice] = "No trips selected or all selected trips are unavailable."
    end
    redirect_to trips_path
  end

  def delete
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:notice] = "Trip cancelled!"
    redirect_to trips_path
  end

  private
  def trip_params
    params.require(:trip).permit(:distance, :car_id, :origin, :destination, :end_time, :start_time, :new_passenger_cost)
  end

  def is_passenger
    unless Passenger.where(trip_id: params[:id], user_id: current_user.id).present?
      flash[:error] = "You aren't on that trip"
      redirect_to trips_path
    end
  end

  def is_owner
    unless Owner.where(car_id: Trip.find(params[:id]).car_id, user_id: current_user.id).present?
      flash[:error] = "You don't own that trip"
      redirect_to trips_path
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<div class="row-fluid">
  <div class="span4 well">
    <%= form_for @trip, url: @url, class: "form" do |f| %>
      <% if @trip.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-block">
          <h4><%= pluralize(@trip.errors.count, "error") %> occurred:</h4>
          <ul>
            <% @trip.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :distance %><br>
        <%= f.number_field :distance, step:0.01, min: 0.01 %>
      </div>

      <div class="form-group">
        <%= f.label :car_id %><br>
        <%= f.select(:car_id, @cars) %>
      </div>

      <div class="form-group">
        <%= f.label :origin %><br>
        <%= f.text_field :origin %>
      </div>

      <div class="form-group">
        <%= f.label :destination %><br>
        <%= f.text_field :destination %>
      </div>

      <div class="form-group">
        <%= f.label :start_time %><br>
        <%= f.datetime_select :start_time %>
      </div>

      <div class="form-group">
        <%= f.label :end_time %><br>
        <%= f.datetime_select :end_time %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-default" %>
      </div>

    <% end %>
  </div>
</div>

app/views/trips/_trip_list_row.html.erb
<tr>
  <td>
    <% if Passenger.where(trip_id: trip.id, user_id: current_user.id).present? %>
      <span class="glyphicon glyphicon-ok"></span>
    <% end %>
  </td>
  <td><%= trip.origin %></td>
  <td><%= trip.destination %></td>
  <td><%= trip.start_time.to_formatted_s(:short) %></td>
  <td><%= trip.end_time.to_formatted_s(:short) %></td>
  <td><%= trip.distance %></td>
  <td>
    <%= link_to "Details", details_trip_path(id: trip.id), class: "btn btn-info", data: {no_turbolink: true} %>
    <!-- if the current user is a passenger on this trip -->
    <% if Passenger.where(trip_id: trip.id, user_id: current_user.id).present? %>
      <!-- if the current user is an owner on this trip -->
      <% if Owner.where(user_id: current_user.id, car_id: trip.car_id).exists? %>
        <!-- owner has the ability to edit the trip -->
        <%= link_to "Edit", edit_trip_path(id: trip.id), class: "btn btn-warning", data: {no_turbolink: true} %>
        <!-- if the current user is NOT the last owner on this trip -->
        <% if Owner.where(car_id: trip.car_id, user_id: Passenger.where(trip_id: trip.id).pluck(:user_id)).count > 1 %>
          <%= link_to "Leave", decrement_path(id: trip.id), class: "btn btn-danger" %>
        <% end %>
        <!-- current user is an owner hence he can "complete" the trip whenever he chooses to -->
        <%= link_to "Complete", complete_loans_path(trip_id: trip.id), class: "btn btn-success", data: {no_turbolink: true} %>
        <!-- current user is an owner hence he can "delete" the trip whenever he chooses to -->
        <%= link_to "Cancel", trip_path(id: trip.id), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
      <% else %>
        <!-- current user is not an owner on this trip so he can leave always -->
        <%= link_to "Leave", decrement_path(id: trip.id), class: "btn btn-danger" %>
      <% end %>
    <% else %>
      <!-- if current user is not a passenger on the trip and the trip still has seats remaining -->
      <% if Passenger.where(trip_id: trip.id).count < Car.find(trip.car_id).seats %>
        <%= check_box_tag "trip_ids[]", trip.id, false, id: "trip_#{trip.id}" %>
        <%= link_to "Join", increment_path(id: trip.id), class: "btn btn-primary" %>
      <% else %>
        <button class="btn btn-primary disabled"><i class="glyphicon glyphicon-lock"></i>Join</button>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/trips/delete.html.erb
<h1>Trips#delete</h1>
<p>Find me in app/views/trips/delete.html.erb</p>

app/views/trips/edit.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <h1>Trips</h1>
  <p>Modify your trip details.</p>
</div>

<%= render 'form' %>

app/views/trips/index.html.erb
<div class="jumbotron">
  <h1>Trips</h1>
  <p>Travel to any place of your choice.</p>
</div>

<%= form_tag(join_multiple_trips_path, method: :post) do %>
  <div class="row-fluid">
    <table class="table">
      <thead>
        <th>  </th>
        <th> Origin </th>
        <th> Destination </th>
        <th> Start Time </th>
        <th> End Time </th>
        <th> Distance </th>
        <th> Actions </th>
      </thead>
      <tbody>
        <% @trips.each do |trip| %>
          <% if not trip.completed %>
            <%= render partial: 'trips/trip_list_row', locals: {trip: trip} %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <p>
      <span class="glyphicon glyphicon-lock"></span> Trip is full.
      <span class="glyphicon glyphicon-ok"></span> You're on this trip.
    </p>
    <%= submit_tag "Join Selected Trips", class: "btn btn-primary", id: "join-multiple-btn" %>
  </div>
<% end %>

app/views/trips/new.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <h1>Trips</h1>
  <p>Create your trip in a matter of seconds.</p>
</div>

<%= render 'form' %>

app/views/trips/show.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <h1>Your Trip</h1>
  <p>Details about your trip.</p>
</div>

Travelling from <%= @trip.origin %>
on <%= @trip.start_time %>.

<br>

Arriving at <%= @trip.destination %> on <%= @trip.end_time %>

<br>

This trip is expected to cost <%= number_to_currency(@trip.total_trip_cost/@passengers.count) %>.

<br>
Passengers on this trip are:
<% @passengers.each do |passenger| %>
    <br>
    <%= User.find(passenger.user_id).name %>
<% end %>
<br>
<b>Note:</b> Price is tentative and may change as people join/leave the trip.

<br>
The car for this trip will be a <%= @car.year %> <%= @car.make %> <%= @car.model %>