config/routes.rb
ShareCar::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'main#index'
  post "owners/new", to: "owners#create"
  resources :owners
  post "cars/new", to: "cars#create"
  resources :cars do
    member do
      delete "delete"
    end
  end
  get "loans/splitwise_callback", to: "loans#splitwise_callback"
  post "loans/new", to: "loans#create"
  resources :loans do
    member do
      delete "delete"
    end
    collection do
      get "create_multiple", as: :complete
    end
  end
  get "trips/increment", as: :increment
  get "trips/decrement", as: :decrement
  post "trips/new", to: "trips#create"
  resources :trips do
    member do
      get "show", as: :details
    end
    collection do
      post "join_multiple"
    end
  end

end

app/models/loan.rb
class Loan < ActiveRecord::Base
    belongs_to :borrower, :class_name => 'User', :foreign_key => 'borrower_id'
    belongs_to :lender, :class_name => 'User', :foreign_key => 'lender_id'
    belongs_to :trip
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController

  def index
    @borrowed = Loan.where(borrower_id: current_user.id)
    @loaned = Loan.where(lender_id: current_user.id)
    @bgroup = @borrowed.group(:lender_id).sum(:amount)
    @lgroup = @loaned.group(:borrower_id).sum(:amount)
    @bgroup.each do |k,v|
        if @lgroup.has_key? k
            if v > @lgroup[k]
                # Adjust the borrowed amount since a smaller amount was "lent"
                @bgroup[k] -= @lgroup[k]
                @lgroup[k] = 0
            elsif v < @lgroup[k]
                @lgroup[k] -= @bgroup[k]
                @bgroup[k] = 0
            else
                # Equal amount borrowed and lent
                @bgroup[k] = 0
                @lgroup[k] = 0
            end
        end
    end
    @bgroup.delete_if { |k, v| v == 0 }
    @lgroup.delete_if { |k, v| v == 0 }
    @loan_history = Loan.where("borrower_id = ? OR lender_id = ?", current_user.id, current_user.id).order(created_at: :desc)
  end

  def show
  end

  def new
    @loan = Loan.new
  end

  def create_multiple
    @trip = Trip.find(params[:trip_id])
    @trip.completed = true
    @trip.save
    owners = Owner.where(car_id: @trip.car_id).pluck(:user_id)
    passengers = Passenger.where(trip_id: @trip.id).where('user_id != ?', owners).pluck(:user_id)
    num_owners = owners.length
    num_passengers = passengers.length
    cost = num_passengers > 0 ? @trip.total_trip_cost/(num_owners*num_passengers) : 0
    owners.each do |o|
      passengers.each do |p|
        Loan.create(borrower_id: p, lender_id: o, trip_id: @trip.id, amount: cost/(num_passengers*num_owners))
      end
    end
    redirect_to loans_path
  end

  def edit
  end

  def delete
    user = User.find(params[:id])
    Loan.destroy_all(borrower_id: current_user.id, lender_id: user.id)
    Loan.destroy_all(borrower_id: user.id, lender_id: current_user.id)
    flash[:notice] = "Transaction completed."
    redirect_to loans_path
  end

  private

  def loan_params
    params.require(:loan).permit(:borrower,:lender,:amount)
  end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-block">
      <h4><%= pluralize(@loan.errors.count, "error") %> occurred:</h4>
      <ul>
        <% @loan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="loanee">
    <%= f.label :borrower_id %><br>
    <%= f.number_field :borrower_id %>
  </div>
  
  <div class="loaner">
    <%= f.label :lender_id %><br>
    <%= f.number_field :lender_id %>
  </div>

  <div class="amount">
    <%= f.label :amount %><br>
    <%= f.number_field :amount, :step => 0.01 %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/delete.html.erb
<h1>Loans#delete</h1>
<p>Find me in app/views/loans/delete.html.erb</p>

app/views/loans/edit.html.erb
<h1>Loans#edit</h1>
<p>Find me in app/views/loans/edit.html.erb</p>

app/views/loans/index.html.erb
<div class="jumbotron">
  <h1>Expenses</h1>
</div>

<% if @bgroup.present? %>
  <h3>Amounts You Owe</h3>
  <div class="row-fluid">
    <table class="table">
      <thead>
        <th>You owe</th>
        <th>Amount</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% @bgroup.each do |k, v| %>
          <tr>
            <td><%= User.find(k).name %></td>
            <td><%= number_to_currency(v) %></td>
            <td><%= link_to "Settle", delete_loan_path(id: k), method: :delete, data: {confirm: 'Settle the debt?'}, class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<% if @lgroup.present? %>
  <h3>Amounts Owed to You</h3>
  <div class="row-fluid">
    <table class="table">
      <thead>
        <th>They owe you</th>
        <th>Amount</th>
        <th>Action</th>
      </thead>
      <tbody>
        <% @lgroup.each do |k, v| %>
          <tr>
            <td><%= User.find(k).name %></td>
            <td><%= number_to_currency(v) %></td>
            <td><%= link_to "Settle", delete_loan_path(id: k), method: :delete, data: {confirm: 'Settle the debt?'}, class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<% if @bgroup.blank? && @lgroup.blank? %>
  <div class="well">
    <p>No outstanding balances. You're all settled up!</p>
  </div>
<% end %>

<hr>

<h3>Financial History</h3>
<% if @loan_history.present? %>
  <div class="row-fluid">
    <table class="table table-striped">
      <thead>
        <th>Date</th>
        <th>Type</th>
        <th>Person</th>
        <th>Amount</th>
        <th>Trip</th>
      </thead>
      <tbody>
        <% @loan_history.each do |loan| %>
          <tr>
            <td><%= loan.created_at.to_formatted_s(:short) %></td>
            <% if loan.borrower_id == current_user.id %>
              <td><span class="label label-danger">Borrowed</span></td>
              <td><%= loan.lender.name %></td>
            <% else %>
              <td><span class="label label-success">Lent</span></td>
              <td><%= loan.borrower.name %></td>
            <% end %>
            <td><%= number_to_currency(loan.amount) %></td>
            <td><%= link_to "Trip ##{loan.trip_id}", details_trip_path(id: loan.trip_id), data: {no_turbolink: true} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="well">
    <p>No financial history yet. Complete a trip to see transactions here.</p>
  </div>
<% end %>

app/views/loans/new.html.erb
<h1>Loans#new</h1>
<p>Find me in app/views/loans/new.html.erb</p>
<%= render 'form' %>

app/views/loans/show.html.erb
<h1>Loans#show</h1>
<p>Find me in app/views/loans/show.html.erb</p>

app/views/loans/splitwise_callback.html.erb
<p>How in the world did you reach here!?</p>