config/routes.rb
ShareCar::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'main#index'
  post "owners/new", to: "owners#create"
  resources :owners
  post "cars/new", to: "cars#create"
  resources :cars do
    member do
      delete "delete"
    end
  end
  get "loans/splitwise_callback", to: "loans#splitwise_callback"
  post "loans/new", to: "loans#create"
  resources :loans do
    member do
      delete "delete"
    end
    collection do
      get "create_multiple", as: :complete
    end
  end
  get "trips/increment", as: :increment
  get "trips/decrement", as: :decrement
  post "trips/new", to: "trips#create"
  resources :trips do
    member do
      get "show", as: :details
    end
    collection do
      post "join_multiple"
    end
  end

end

app/models/car.rb
class Car < ActiveRecord::Base
    has_many :trips
    has_many :owner, dependent: :delete_all
    validates :make, :model, :year, :seats, :cost_per_mile, presence: true
    validates :cost_per_mile, numericality: {greater_than: 0}
    validates :seats, numericality: {only_integer: true, greater_than: 0}
    validates :year, numericality: {only_integer: true, greater_than: 1900}

    def human_name
    	"#{self.make} #{self.model} #{self.year}"
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :owns_car, only: [:edit, :update, :destroy, :delete]

  def index
    @cars = Car.where(id: Owner.where(user_id: current_user.id).pluck(:car_id))
  end

  def new
    @car = Car.new
    @url = cars_url
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      @owner = Owner.new(car_id: @car.id, user_id: current_user.id)
      if @owner.save
        redirect_to cars_path
      else
        flash.now[:alert] = "Could not assign car ownership. Please try again."
        render 'new'
      end
    else
      flash.now[:alert] = "Could not save car. Please check the errors below."
      render 'new'
    end
  end

  def edit
    @car = Car.where(id: params[:id]).first
    @url = car_url
  end

  def update
    car = Car.where(id: params[:id]).first
    if car.update_attributes(car_params)
      flash[:success] = "Modified the details!"
    else
      flash[:alert] = "Could not update car details. Please check the details and try again."
    end
    redirect_to cars_path
  end

  def delete
    car = Car.where(id: params[:id]).first
    car.destroy
    flash[:notice] = "Car and all its owners forgotten."
    redirect_to cars_path
  end

  private
  def car_params
    params.require(:car).permit(:make, :model, :year, :cost_per_mile, :seats)
  end

  def owns_car
    unless Owner.where(car_id: params[:id], user_id: current_user.id).present?
      flash[:alert] = "You don't own such a car!"
      redirect_to trips_path
    end
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<div class="row-fluid">
  <div class="span4 well">
    <div class="form">
      <%= form_for (@car), url: @url do |f| %>
        <% if @car.errors.any? %>
          <div id="error_explanation" class="alert alert-danger alert-block">
            <h4><%= pluralize(@car.errors.count, "error") %> occurred:</h4>
            <ul>
              <% @car.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :cost_per_mile %><br>
          <%= f.number_field :cost_per_mile, step: 0.0001 %>
        </div>

        <div class="form-group">
          <%= f.label :make %><br>
          <%= f.text_field :make %>
        </div>

        <div class="form-group">
          <%= f.label :model %><br>
          <%= f.text_field :model %>
        </div>

        <div class="form-group">
          <%= f.label :year %><br>
          <%= f.number_field :year %>
        </div>

        <div class="form-group">
          <%= f.label :seats %><br>
          <%= f.number_field :seats, min: 1 %>
        </div>
        
        <%= f.submit options={class: "btn btn-default"} %>

      <% end %>
    </div>
  </div>
</div>

app/views/cars/delete.html.erb
<h1>Cars#delete</h1>
<p>Find me in app/views/cars/delete.html.erb</p>

app/views/cars/edit.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <h1>Cars</h1>
  <p>Modify your car here.</p>
</div>

<%= render 'form' %>

app/views/cars/index.html.erb
<div class="jumbotron">
  <h1><i class="fa fa-car"></i> Your Garage</h1>
  <p>Manage your vehicles here.</p>
</div>

<div class="row-fluid">
  <div class="pull-right" style="margin-bottom: 15px;">
    <%= link_to new_car_path, class: "btn btn-success btn-lg", data: {no_turbolink: true} do %>
      <i class="glyphicon glyphicon-plus"></i> Register New Car
    <% end %>
  </div>
</div>

<% if @cars.empty? %>
  <div class="well text-center">
    <h3>Your garage is empty!</h3>
    <p>Register your first car to start creating trips.</p>
    <%= link_to new_car_path, class: "btn btn-primary btn-lg", data: {no_turbolink: true} do %>
      <i class="glyphicon glyphicon-plus"></i> Register Your First Car
    <% end %>
  </div>
<% else %>
  <div class="row">
    <% @cars.each do |c| %>
      <div class="col-md-4 col-sm-6" style="margin-bottom: 20px;">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><strong><%= c.make %> <%= c.model %></strong></h3>
          </div>
          <div class="panel-body">
            <p><i class="glyphicon glyphicon-calendar"></i> <strong>Year:</strong> <%= c.year %></p>
            <p><i class="glyphicon glyphicon-user"></i> <strong>Seats:</strong> <%= c.seats %></p>
            <p><i class="glyphicon glyphicon-usd"></i> <strong>Cost per mile:</strong> <%= number_to_currency(c.cost_per_mile) %></p>
            <% trip_count = Trip.where(car_id: c.id).count %>
            <p><i class="glyphicon glyphicon-road"></i> <strong>Trips:</strong> <%= trip_count %></p>
          </div>
          <div class="panel-footer">
            <% if trip_count == 0 %>
              <%= link_to edit_car_path(id: c.id), class: "btn btn-info", data: {no_turbolink: true} do %>
                <i class="glyphicon glyphicon-pencil"></i> Edit
              <% end %>
              <%= link_to delete_car_path(id: c.id), method: "delete", data: {confirm: 'Are you sure you want to delete this car?'}, class: "btn btn-danger" do %>
                <i class="glyphicon glyphicon-trash"></i> Delete
              <% end %>
            <% else %>
              <span class="text-muted">Car has trips and cannot be modified</span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/cars/new.html.erb
<!-- Jumbotron -->
<div class="jumbotron">
  <h1>Cars</h1>
  <p>Register your car here.</p>
</div>

<%= render 'form' %>