config/routes.rb
ShareCar::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'main#index'
  post "owners/new", to: "owners#create"
  resources :owners
  post "cars/new", to: "cars#create"
  resources :cars do
    member do
      delete "delete"
    end
  end
  get "loans/splitwise_callback", to: "loans#splitwise_callback"
  post "loans/new", to: "loans#create"
  resources :loans do
    member do
      delete "delete"
    end
    collection do
      get "create_multiple", as: :complete
    end
  end
  get "trips/increment", as: :increment
  get "trips/decrement", as: :decrement
  post "trips/new", to: "trips#create"
  resources :trips do
    member do
      get "show", as: :details
    end
    collection do
      post "join_multiple"
    end
  end

end

app/views/layouts/_flash_message.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert <%= flash_class(key).to_s %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar_fixed_top_logged_in.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to raw("<i class='fa fa-car'></i> Trippa"), trips_path, {class:"navbar-brand page-scroll", data:{no_turbolink: true}} %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><strong><span class="navbar-text"><%= timepiece Time.zone.name %> <%= Time.zone.to_s %></span></strong></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><strong><span class="navbar-text"><%= current_user.name %></span></strong></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Trips</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Trip", new_trip_path, data:{no_turbolink: true} %></li>
            <li><%= link_to "View/Modify Trip", trips_path, data:{no_turbolink: true} %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cars</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Car", new_car_path, data:{no_turbolink: true} %></li>
            <li><%= link_to "View/Modify Car", cars_path, data:{no_turbolink: true} %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Owners</a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add Owner", new_owner_path, data:{no_turbolink: true} %></li>
          </ul>
        </li>
        <li><%= link_to "Expenses", loans_path, data:{no_turbolink: true} %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</div>

app/views/layouts/_navbar_fixed_top_sessions.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-car"></i>  <span class="light">Trippa</span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><strong><span class="navbar-text"><%= timepiece Time.zone.name %> <%= Time.zone.to_s %></span></strong></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Login", new_user_session_path, data:{no_turbolink: true} %></li>
        <li><%= link_to "Register", new_user_registration_path, data:{no_turbolink: true} %></li>
        <li><%= link_to "Homepage", root_path, data:{no_turbolink: true} %></li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Trippa</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/flash_message' %>
  <%= yield %>
  <!-- Footer -->
  <hr>
  <footer>
      <div class="container text-center">
          <p>Copyright &copy; Trippa 2026</p>
      </div>
  </footer>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/cars.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Trippa-Cars</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "navbar-fixed-top" %>
  <%= stylesheet_link_tag "cars" %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top">
  <div class="container">
    <%= render 'layouts/navbar_fixed_top_logged_in' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </div>
  <!-- Footer -->
  <hr>
  <footer>
      <div class="container text-center">
          <p>Copyright &copy; Trippa 2026</p>
      </div>
  </footer>
  <%= javascript_include_tag "cars", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/loans.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Trippa-Loans</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "navbar-fixed-top" %>
  <%= stylesheet_link_tag "loans" %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top">
  <div class="container">
    <%= render 'layouts/navbar_fixed_top_logged_in' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </div>
  <!-- Footer -->
  <hr>
  <footer>
      <div class="container text-center">
          <p>Copyright &copy; Trippa 2026</p>
      </div>
  </footer>
  <%= javascript_include_tag "loans", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Trippa</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "main" %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <div class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand page-scroll" href="#page-top">
          <i class="fa fa-car"></i>  <span class="light">Trippa</span>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-main-collapse">
        <ul class="nav navbar-nav">
            <li><span class="navbar-text"><%= timepiece Time.zone.name %> <%= Time.zone.to_s %></span></li>
          </ul>
        <ul class="nav navbar-nav navbar-right">
          <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
          <li class="hidden">
            <a href="#page-top"></a>
          </li>
          <% if user_signed_in? %>
            <li>
              <strong><span class="navbar-text"><%= current_user.name %></span></strong>
            </li>
            <li>
              <%= link_to "Enter", trips_path, data: {no_turbolink: true} %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login", new_user_session_path, data:{no_turbolink: true} %>
            </li>
            <li>
              <%= link_to "Register", new_user_registration_path, data:{no_turbolink: true} %>
            </li>
          <% end %>
          <li>
            <a class="page-scroll" href="#about">About</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </div>
  <%= yield %>
  <!-- Footer -->
  <footer>
      <div class="container text-center">
          <p>Copyright &copy; Trippa 2026</p>
      </div>
  </footer>
  <%= javascript_include_tag "main", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/owners.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Trippa-Owners</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "navbar-fixed-top" %>
  <%= stylesheet_link_tag "owners" %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top">
  <div class="container">
    <%= render 'layouts/navbar_fixed_top_logged_in' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </div>
  <!-- Footer -->
  <hr>
  <footer>
      <div class="container text-center">
          <p>Copyright &copy; Trippa 2026</p>
      </div>
  </footer>
  <%= javascript_include_tag "owners", "data-turbolinks-track" => true %>
</body>
</html>

app/views/layouts/trips.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Trippa-Trips</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "navbar-fixed-top" %>
  <%= stylesheet_link_tag "trips" %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top">
  <div class="container">
    <%= render 'layouts/navbar_fixed_top_logged_in' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
  </div>
  <!-- Footer -->
  <hr>
  <footer>
      <div class="container text-center">
          <p>Copyright &copy; Trippa 2026</p>
      </div>
  </footer>
  <%= javascript_include_tag "trips", "data-turbolinks-track" => true %>
</body>
</html>